name: AutoScheduling

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  AutoScheduling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Execute Script
        run: python main.py -u "${{ secrets.Username }}" -p "${{ secrets.Password }}"

      - name: Upload Log File
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: agendamento.log

      - name: Send success notification
        if: success()
        run: |
          python - <<EOF
          import smtplib
          from email.mime.text import MIMEText
          from email.mime.multipart import MIMEMultipart

          gmail_user = "${{ secrets.GMAIL_USERNAME }}"
          gmail_password = "${{ secrets.GMAIL_PASSWORD }}"
          to = "${{ secrets.EMAIL_TO }}"
          subject = "Agendamento Realizado"
          body = "Agendamento realizado com sucesso."

          msg = MIMEMultipart()
          msg['From'] = "${{ secrets.EMAIL_FROM }}"
          msg['To'] = to
          msg['Subject'] = subject
          msg.attach(MIMEText(body, 'plain'))

          try:
              server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
              server.ehlo()
              server.login(gmail_user, gmail_password)
              text = msg.as_string()
              server.sendmail(gmail_user, to, text)
              server.close()
              print("Email sent successfully")
          except Exception as e:
              print(f"Failed to send email: {str(e)}")
          EOF

      - name: Send failure notification
        if: failure()
        run: |
          python - <<EOF
          import smtplib
          from email.mime.text import MIMEText
          from email.mime.multipart import MIMEMultipart

          gmail_user = "${{ secrets.GMAIL_USERNAME }}"
          gmail_password = "${{ secrets.GMAIL_PASSWORD }}"
          to = "${{ secrets.EMAIL_TO }}"
          subject = "Agendamento Não Realizado"
          body = "Falha ao realizar agendamento. Verifique os logs para mais informações."

          msg = MIMEMultipart()
          msg['From'] = "${{ secrets.EMAIL_FROM }}"
          msg['To'] = to
          msg['Subject'] = subject
          msg.attach(MIMEText(body, 'plain'))

          try:
              server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
              server.ehlo()
              server.login(gmail_user, gmail_password)
              text = msg.as_string()
              server.sendmail(gmail_user, to, text)
              server.close()
              print("Email sent successfully")
          except Exception as e:
              print(f"Failed to send email: {str(e)}")
          EOF
